#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/huonglam/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/huonglam/Documents/HCMUS/HK1-4/Mobile NC/finalproject_1712061"
export "FLUTTER_TARGET=/Users/huonglam/Documents/HCMUS/HK1-4/Mobile NC/finalproject_1712061/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/huonglam/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/huonglam/Documents/HCMUS/HK1-4/Mobile NC/finalproject_1712061/.dart_tool/package_config.json"
